name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install project dependencies
        run: npm install

      - name: Lint check
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Deploy
        run: npm run deploy
        env:
          VUE_APP_I18N_LOCALE ${{ secrets.VUE_APP_I18N_LOCALE }}
          VUE_APP_I18N_FALLBACK_LOCALE ${{ secrets.VUE_APP_I18N_FALLBACK_LOCALE }}
          VUE_APP_API ${{ secrets.VUE_APP_API }}
